name: Mirror Changes

on:
  push:
    branches:
      - main  

jobs:
  mirror_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout assig3 repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "Mirand Osmani"
          git config --global user.email "osmanimirand@gmail.com"

      - name: Mirror changes to mirror_test repository
        env:
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          git remote add mirror_test https://github.com/MirandO98/mirror_test.git
          git push -u mirror_test HEAD:main  # Push to target branch



          
          
          
          
