name: Mirror Repo to Another Repo

on:
  push:
    branches:
      - main

jobs:
  mirror-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "MirandOsmani"
          git config user.email "osmanimirand@gmail.com"

      - name: Clone target repo
        run: |
          git clone -mirror https://github.com/MirandO98/assigment3.git
          cd assigment3.git
          git remote set-url --push origin https://github.com/MirandO98/mirror_test
          git fetch -p origin
          git push --mirror
          
          

      
