name: Mirror Repository on Push

on:
  push:
    branches:
      - main
     
permissions:
    contents: write
                
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Mirror repository to test_branch
      env:
        TARGET_REPO: 'MirandO98/test_branch' 
        TARGET_BRANCH: 'main'
        SOURCE_DIR: '.' # Current directory
        PAT: ${{ secrets.MIRROR_REPO_TOKEN }}
       
      run: |
        git config --global user.email "osmanimirand@gmail.com"
        git config --global user.name "MirandO98"   
        git clone --mirror https://github.com/MirandO98/assigment3.git
        cd assigment3.git
        git remote set-url --push origin https://github.com/MirandO98/test_branch
        git fetch -p origin
        git push --mirror
        
