name: Mirror Repository on Push

on:
  push:
    branches:
      - main
     
permissions:
    contents: write
                
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Mirror repository to test_branch
      env:
        TARGET_REPO: 'MirandO98/test_branch' 
        TARGET_BRANCH: 'main'
        SOURCE_DIR: '.' # Current directory
        PAT: ${{ secrets.MIRROR_REPO_TOKEN }}
       
      run: |
        git remote add origin https://MirandO98:PERSONAL_ACCESS_TOKEN@github.com/MirandO98/test_branch.git
        git remote set-url origin https://github.com/MirandO98/test_branch.git
        git config --global user.email "osmanimirand@gmail.com" # Replace with your email
        git config --global user.name "Mirand Osmani" # Replace with your name
        git remote add test_branch https://${PAT}@github.com/${TARGET_REPO}.git
        git push test_branch HEAD:${TARGET_BRANCH} --force
