name: Mirror Repo to Another Repo

on:
  push:
    branches:
      - main

jobs:
  mirror-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "MirandOsmani"
          git config user.email "osmanimirand@gmail.com"

      - name: Clone target repo
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/mirror_test

      - name: Mirror files
        run: |
          cd mirror_test
          rm -rf *
          cp -R ../. .
          git add .
          git commit -m "Mirroring from assigment3 repo"
          git push origin main
