name: Mirror testing

on:
  push:
    branches:
      - main

jobs:
  mirror-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to mirror_test repo
      env:
        TARGET_REPO: 'MirandO98/mirror_test'
        TARGET_BRANCH: 'main'
        SOURCE_DIR: '.'
      run: |
        git config --global user.email "osmanimirand@gmail.com"
        git config --global user.name "MirandOsmani"
        # Use secrets.GITHUB_TOKEN directly in the HTTPS URL for authentication
        git remote add target https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${TARGET_REPO}.git
        git push target HEAD:${TARGET_BRANCH} --force
