name: Mirror testing

on:
  push:
    branches:
      - main

jobs:
  mirror-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to mirror_test repo
      env:
        TARGET_REPO: 'MirandO98/mirror_test'
        TARGET_BRANCH: 'main'
        SOURCE_DIR: '.' #root dir.
        PAT: ${{ secrets.PAT }} # Personal secret name - need to add on Github Secrets
      run: |
        git config --global user.email "osmanimirand@gmail.com"
        git config --global user.name "MirandOsmani"
        git remote add target https://${PAT}@github.com/${TARGET_REPO}.git
        git push target HEAD:${TARGET_BRANCH} --force
